name: nau
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  provider: ^6.1.4
  cloud_firestore: ^5.6.6
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.10.1
  http: ^1.3.0
  shared_preferences: ^2.5.3
  socket_io_client: ^3.1.1
  geolocator: ^13.0.4
  ulid: ^2.0.1
  geocoding: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
