buildscript {
    ext.kotlin_version = '1.8.10'

    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.3.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

ext {
    compileSdkVersion = project.hasProperty('compileSdkVersion') ? project.compileSdkVersion.toInteger() : 33
    minSdkVersion = project.hasProperty('minSdkVersion') ? project.minSdkVersion.toInteger() : 23
    targetSdkVersion = project.hasProperty('targetSdkVersion') ? project.targetSdkVersion.toInteger() : 33
}

rootProject.buildDir = "../build"

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
