// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfJ6JHFCsVdpO4Awcj3KqCREbV2gOlQdM',
    appId: '1:546678471148:web:9ec668aba21b22290a28c9',
    messagingSenderId: '546678471148',
    projectId: 'nau1-20eec',
    authDomain: 'nau1-20eec.firebaseapp.com',
    storageBucket: 'nau1-20eec.firebasestorage.app',
    measurementId: 'G-94LXZGJ14X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnafhmFze96Dvw5-jPI29MdhiZWJaO45U',
    appId: '1:546678471148:android:6bd09cdc36aa14760a28c9',
    messagingSenderId: '546678471148',
    projectId: 'nau1-20eec',
    storageBucket: 'nau1-20eec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkyeRodd-6fOeHtekLZVfvK8xyXZmBGH4',
    appId: '1:546678471148:ios:5c87811e14c7fa230a28c9',
    messagingSenderId: '546678471148',
    projectId: 'nau1-20eec',
    storageBucket: 'nau1-20eec.firebasestorage.app',
    iosBundleId: 'com.example.nau',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkyeRodd-6fOeHtekLZVfvK8xyXZmBGH4',
    appId: '1:546678471148:ios:5c87811e14c7fa230a28c9',
    messagingSenderId: '546678471148',
    projectId: 'nau1-20eec',
    storageBucket: 'nau1-20eec.firebasestorage.app',
    iosBundleId: 'com.example.nau',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfJ6JHFCsVdpO4Awcj3KqCREbV2gOlQdM',
    appId: '1:546678471148:web:02f1e3c2fbc8c7ee0a28c9',
    messagingSenderId: '546678471148',
    projectId: 'nau1-20eec',
    authDomain: 'nau1-20eec.firebaseapp.com',
    storageBucket: 'nau1-20eec.firebasestorage.app',
    measurementId: 'G-F2KYR9P7TY',
  );

}